"""Add patch version

Revision ID: 36769a27abbb
Revises: 
Create Date: 2023-05-27 12:09:57.613055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36769a27abbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patch', sa.Column('version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patch', 'version')
    # ### end Alembic commands ###
